namespace Ais.Net.Models.Specs;

using Ais.Net.Models;
using Ais.Net.Models.Abstractions;

using Microsoft.VisualStudio.TestTools.UnitTesting;

using Shouldly;

[TestClass]
public class ShipTypeClassificationTests
{
    [TestMethod]
    [DataRow(0, ShipTypeGroup.NotAvailable)]
    [DataRow(1, ShipTypeGroup.Reserved)]
    [DataRow(19, ShipTypeGroup.Reserved)]
    [DataRow(20, ShipTypeGroup.WingInGroundAll)]
    [DataRow(21, ShipTypeGroup.WingInGroundHazardous)]
    [DataRow(24, ShipTypeGroup.WingInGroundHazardous)]
    [DataRow(25, ShipTypeGroup.WingInGroundReserved)]
    [DataRow(29, ShipTypeGroup.WingInGroundReserved)]
    [DataRow(30, ShipTypeGroup.Fishing)]
    [DataRow(31, ShipTypeGroup.Towing)]
    [DataRow(32, ShipTypeGroup.TowingLengthOver200MOrBreadthOver25M)]
    [DataRow(33, ShipTypeGroup.DredgingOrUnderwaterOps)]
    [DataRow(34, ShipTypeGroup.DivingOps)]
    [DataRow(35, ShipTypeGroup.MilitaryOps)]
    [DataRow(36, ShipTypeGroup.Sailing)]
    [DataRow(37, ShipTypeGroup.PleasureCraft)]
    [DataRow(38, ShipTypeGroup.Reserved)]
    [DataRow(39, ShipTypeGroup.Reserved)]
    [DataRow(40, ShipTypeGroup.HighSpeedCraftAll)]
    [DataRow(41, ShipTypeGroup.HighSpeedCraftHazardous)]
    [DataRow(44, ShipTypeGroup.HighSpeedCraftHazardous)]
    [DataRow(45, ShipTypeGroup.HighSpeedCraftReserved)]
    [DataRow(48, ShipTypeGroup.HighSpeedCraftReserved)]
    [DataRow(49, ShipTypeGroup.HighSpeedCraftNoAdditionalInformation)]   // '9' == "no additional information", matching 69/79/89/99
    [DataRow(50, ShipTypeGroup.PilotVessel)]
    [DataRow(51, ShipTypeGroup.SearchAndRescueVessel)]
    [DataRow(52, ShipTypeGroup.Tug)]
    [DataRow(53, ShipTypeGroup.PortTender)]
    [DataRow(54, ShipTypeGroup.AntiPollutionEquipment)]
    [DataRow(55, ShipTypeGroup.LawEnforcement)]
    [DataRow(56, ShipTypeGroup.SpareLocalVessel)]
    [DataRow(57, ShipTypeGroup.SpareLocalVessel)]
    [DataRow(58, ShipTypeGroup.MedicalTransport)]
    [DataRow(59, ShipTypeGroup.NoncombatantShip)]
    [DataRow(60, ShipTypeGroup.PassengerAll)]
    [DataRow(61, ShipTypeGroup.PassengerHazardous)]
    [DataRow(64, ShipTypeGroup.PassengerHazardous)]
    [DataRow(65, ShipTypeGroup.PassengerReserved)]
    [DataRow(68, ShipTypeGroup.PassengerReserved)]
    [DataRow(69, ShipTypeGroup.PassengerNoAdditionalInformation)]
    [DataRow(70, ShipTypeGroup.CargoAll)]
    [DataRow(71, ShipTypeGroup.CargoHazardous)]
    [DataRow(74, ShipTypeGroup.CargoHazardous)]
    [DataRow(75, ShipTypeGroup.CargoReserved)]
    [DataRow(78, ShipTypeGroup.CargoReserved)]
    [DataRow(79, ShipTypeGroup.CargoNoAdditionalInformation)]
    [DataRow(80, ShipTypeGroup.TankerAll)]
    [DataRow(81, ShipTypeGroup.TankerHazardous)]
    [DataRow(84, ShipTypeGroup.TankerHazardous)]
    [DataRow(85, ShipTypeGroup.TankerReserved)]
    [DataRow(88, ShipTypeGroup.TankerReserved)]
    [DataRow(89, ShipTypeGroup.TankerNoAdditionalInformation)]
    [DataRow(90, ShipTypeGroup.OtherAll)]
    [DataRow(91, ShipTypeGroup.OtherHazardous)]
    [DataRow(94, ShipTypeGroup.OtherHazardous)]
    [DataRow(95, ShipTypeGroup.OtherReserved)]
    [DataRow(98, ShipTypeGroup.OtherReserved)]
    [DataRow(99, ShipTypeGroup.OtherNoAdditionalInformation)]
    [DataRow(100, ShipTypeGroup.NotAvailable)]
    [DataRow(-1, ShipTypeGroup.NotAvailable)]
    public void ToShipTypeGroupClassifiesRawShipTypeCode(int shipType, ShipTypeGroup expected)
    {
        shipType.ToShipTypeGroup().ShouldBe(expected);
    }

    [TestMethod]
    [DataRow(ShipTypeGroup.NotAvailable, ShipTypeCategory.NotAvailable)]
    [DataRow(ShipTypeGroup.Reserved, ShipTypeCategory.Reserved)]
    [DataRow(ShipTypeGroup.WingInGroundAll, ShipTypeCategory.WingInGround)]
    [DataRow(ShipTypeGroup.WingInGroundHazardous, ShipTypeCategory.WingInGround)]
    [DataRow(ShipTypeGroup.WingInGroundReserved, ShipTypeCategory.WingInGround)]
    [DataRow(ShipTypeGroup.Fishing, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.Towing, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.TowingLengthOver200MOrBreadthOver25M, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.DredgingOrUnderwaterOps, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.DivingOps, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.MilitaryOps, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.Sailing, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.PleasureCraft, ShipTypeCategory.SpecialCategory3)]
    [DataRow(ShipTypeGroup.HighSpeedCraftAll, ShipTypeCategory.HighSpeedCraft)]
    [DataRow(ShipTypeGroup.HighSpeedCraftHazardous, ShipTypeCategory.HighSpeedCraft)]
    [DataRow(ShipTypeGroup.HighSpeedCraftReserved, ShipTypeCategory.HighSpeedCraft)]
    [DataRow(ShipTypeGroup.HighSpeedCraftNoAdditionalInformation, ShipTypeCategory.HighSpeedCraft)]
    [DataRow(ShipTypeGroup.PilotVessel, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.SearchAndRescueVessel, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.Tug, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.PortTender, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.AntiPollutionEquipment, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.LawEnforcement, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.SpareLocalVessel, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.MedicalTransport, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.NoncombatantShip, ShipTypeCategory.SpecialCategory5)]
    [DataRow(ShipTypeGroup.PassengerAll, ShipTypeCategory.Passenger)]
    [DataRow(ShipTypeGroup.PassengerHazardous, ShipTypeCategory.Passenger)]
    [DataRow(ShipTypeGroup.PassengerReserved, ShipTypeCategory.Passenger)]
    [DataRow(ShipTypeGroup.PassengerNoAdditionalInformation, ShipTypeCategory.Passenger)]
    [DataRow(ShipTypeGroup.CargoAll, ShipTypeCategory.Cargo)]
    [DataRow(ShipTypeGroup.CargoHazardous, ShipTypeCategory.Cargo)]
    [DataRow(ShipTypeGroup.CargoReserved, ShipTypeCategory.Cargo)]
    [DataRow(ShipTypeGroup.CargoNoAdditionalInformation, ShipTypeCategory.Cargo)]
    [DataRow(ShipTypeGroup.TankerAll, ShipTypeCategory.Tanker)]
    [DataRow(ShipTypeGroup.TankerHazardous, ShipTypeCategory.Tanker)]
    [DataRow(ShipTypeGroup.TankerReserved, ShipTypeCategory.Tanker)]
    [DataRow(ShipTypeGroup.TankerNoAdditionalInformation, ShipTypeCategory.Tanker)]
    [DataRow(ShipTypeGroup.OtherAll, ShipTypeCategory.Other)]
    [DataRow(ShipTypeGroup.OtherHazardous, ShipTypeCategory.Other)]
    [DataRow(ShipTypeGroup.OtherReserved, ShipTypeCategory.Other)]
    [DataRow(ShipTypeGroup.OtherNoAdditionalInformation, ShipTypeCategory.Other)]
    [DataRow((ShipTypeGroup)999, ShipTypeCategory.NotAvailable)]     // an unrecognised group falls back to NotAvailable
    public void ToShipTypeCategoryMapsGroupToCategory(ShipTypeGroup group, ShipTypeCategory expected)
    {
        group.ToShipTypeCategory().ShouldBe(expected);
    }

    [TestMethod]
    [DataRow(0, ShipTypeCategory.NotAvailable)]
    [DataRow(30, ShipTypeCategory.SpecialCategory3)]
    [DataRow(40, ShipTypeCategory.HighSpeedCraft)]
    [DataRow(50, ShipTypeCategory.SpecialCategory5)]
    [DataRow(60, ShipTypeCategory.Passenger)]
    [DataRow(70, ShipTypeCategory.Cargo)]
    [DataRow(80, ShipTypeCategory.Tanker)]
    [DataRow(90, ShipTypeCategory.Other)]
    public void ToShipTypeCategoryClassifiesShipTypeEnumViaItsGroup(int shipType, ShipTypeCategory expected)
    {
        ((ShipType)shipType).ToShipTypeCategory().ShouldBe(expected);
    }

    [TestMethod]
    [DataRow(-5, "Not available")]                                                          // below the valid range
    [DataRow(0, "Not available")]
    [DataRow(1, "Reserved for future use")]
    [DataRow(10, "Reserved for future use")]
    [DataRow(19, "Reserved for future use")]
    [DataRow(20, "Wing in ground(WIG), all ships of this type")]
    [DataRow(21, "Wing in ground(WIG), Hazardous category A")]
    [DataRow(22, "Wing in ground(WIG), Hazardous category B")]
    [DataRow(23, "Wing in ground(WIG), Hazardous category C")]
    [DataRow(24, "Wing in ground(WIG), Hazardous category D")]
    [DataRow(25, "Wing in ground(WIG), Reserved for future use")]
    [DataRow(29, "Wing in ground(WIG), Reserved for future use")]
    [DataRow(30, "Fishing")]
    [DataRow(31, "Towing")]
    [DataRow(32, "Towing: length exceeds 200m or breadth exceeds 25m")]
    [DataRow(33, "Dredging or underwater ops")]
    [DataRow(34, "Diving ops")]
    [DataRow(35, "Military ops")]
    [DataRow(36, "Sailing")]
    [DataRow(37, "Pleasure Craft")]
    [DataRow(38, "Reserved")]
    [DataRow(39, "Reserved")]
    [DataRow(40, "High speed craft(HSC), all ships of this type")]
    [DataRow(41, "High speed craft(HSC), Hazardous category A")]
    [DataRow(42, "High speed craft(HSC), Hazardous category B")]
    [DataRow(43, "High speed craft(HSC), Hazardous category C")]
    [DataRow(44, "High speed craft(HSC), Hazardous category D")]
    [DataRow(45, "High speed craft(HSC), Reserved for future use")]
    [DataRow(48, "High speed craft(HSC), Reserved for future use")]
    [DataRow(49, "High speed craft(HSC), No additional information")]
    [DataRow(50, "Pilot Vessel")]
    [DataRow(51, "Search and Rescue vessel")]
    [DataRow(52, "Tug")]
    [DataRow(53, "Port Tender")]
    [DataRow(54, "Anti - pollution equipment")]
    [DataRow(55, "Law Enforcement")]
    [DataRow(56, "Spare - Local Vessel")]
    [DataRow(57, "Spare - Local Vessel")]
    [DataRow(58, "Medical Transport")]
    [DataRow(59, "Noncombatant ship according to RR Resolution No. 18")]
    [DataRow(60, "Passenger, all ships of this type")]
    [DataRow(61, "Passenger, Hazardous category A")]
    [DataRow(62, "Passenger, Hazardous category B")]
    [DataRow(63, "Passenger, Hazardous category C")]
    [DataRow(64, "Passenger, Hazardous category D")]
    [DataRow(65, "Passenger, Reserved for future use")]
    [DataRow(68, "Passenger, Reserved for future use")]
    [DataRow(69, "Passenger, No additional information")]
    [DataRow(70, "Cargo, all ships of this type")]
    [DataRow(71, "Cargo, Hazardous category A")]
    [DataRow(72, "Cargo, Hazardous category B")]
    [DataRow(73, "Cargo, Hazardous category C")]
    [DataRow(74, "Cargo, Hazardous category D")]
    [DataRow(75, "Cargo, Reserved for future use")]
    [DataRow(78, "Cargo, Reserved for future use")]
    [DataRow(79, "Cargo, No additional information")]
    [DataRow(80, "Tanker, all ships of this type")]
    [DataRow(81, "Tanker, Hazardous category A")]
    [DataRow(82, "Tanker, Hazardous category B")]
    [DataRow(83, "Tanker, Hazardous category C")]
    [DataRow(84, "Tanker, Hazardous category D")]
    [DataRow(85, "Tanker, Reserved for future use")]
    [DataRow(88, "Tanker, Reserved for future use")]
    [DataRow(89, "Tanker, No additional information")]
    [DataRow(90, "Other Type, all ships of this type")]
    [DataRow(91, "Other Type, Hazardous category A")]
    [DataRow(92, "Other Type, Hazardous category B")]
    [DataRow(93, "Other Type, Hazardous category C")]
    [DataRow(94, "Other Type, Hazardous category D")]
    [DataRow(95, "Other Type, Reserved for future use")]
    [DataRow(98, "Other Type, Reserved for future use")]
    [DataRow(99, "Other Type, no additional information")]
    [DataRow(100, "Not available")]                                                         // above the valid range

    // Remaining interior values of each "Reserved for future use" band — every code has its
    // own arm in the source, so these are included to exercise all of them.
    [DataRow(26, "Wing in ground(WIG), Reserved for future use")]
    [DataRow(27, "Wing in ground(WIG), Reserved for future use")]
    [DataRow(28, "Wing in ground(WIG), Reserved for future use")]
    [DataRow(46, "High speed craft(HSC), Reserved for future use")]
    [DataRow(47, "High speed craft(HSC), Reserved for future use")]
    [DataRow(66, "Passenger, Reserved for future use")]
    [DataRow(67, "Passenger, Reserved for future use")]
    [DataRow(76, "Cargo, Reserved for future use")]
    [DataRow(77, "Cargo, Reserved for future use")]
    [DataRow(86, "Tanker, Reserved for future use")]
    [DataRow(87, "Tanker, Reserved for future use")]
    [DataRow(96, "Other Type, Reserved for future use")]
    [DataRow(97, "Other Type, Reserved for future use")]
    public void ToShipTypeDescriptionReturnsHumanReadableText(int shipType, string expected)
    {
        shipType.ToShipTypeDescription().ShouldBe(expected);
    }

    [TestMethod]
    public void ToShipTypeGroupAcceptsTheShipTypeEnum()
    {
        ((ShipType)60).ToShipTypeGroup().ShouldBe(ShipTypeGroup.PassengerAll);
    }
}
